# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/ece554_final_project/workout_classifier/workout_classifier.srcs/sources_1/bd/workout_classifier/ip/workout_classifier_mlp_controller_0_2/workout_classifier_mlp_controller_0_2.xci
# IP: The module: 'workout_classifier_mlp_controller_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: z:/ece554_final_project/workout_classifier/workout_classifier.gen/sources_1/bd/workout_classifier/ip/workout_classifier_mlp_controller_0_2/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: z:/ece554_final_project/workout_classifier/workout_classifier.gen/sources_1/bd/workout_classifier/ip/workout_classifier_mlp_controller_0_2/src/dsp_macro_0_1/dsp_macro_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# XDC: z:/ece554_final_project/workout_classifier/workout_classifier.gen/sources_1/bd/workout_classifier/ip/workout_classifier_mlp_controller_0_2/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc

# IP: z:/ece554_final_project/workout_classifier/workout_classifier.srcs/sources_1/bd/workout_classifier/ip/workout_classifier_mlp_controller_0_2/workout_classifier_mlp_controller_0_2.xci
# IP: The module: 'workout_classifier_mlp_controller_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: z:/ece554_final_project/workout_classifier/workout_classifier.gen/sources_1/bd/workout_classifier/ip/workout_classifier_mlp_controller_0_2/src/blk_mem_gen_0_1/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: z:/ece554_final_project/workout_classifier/workout_classifier.gen/sources_1/bd/workout_classifier/ip/workout_classifier_mlp_controller_0_2/src/dsp_macro_0_1/dsp_macro_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dsp_macro_0 || ORIG_REF_NAME==dsp_macro_0} -quiet] -quiet

# XDC: z:/ece554_final_project/workout_classifier/workout_classifier.gen/sources_1/bd/workout_classifier/ip/workout_classifier_mlp_controller_0_2/src/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc
