# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: z:/ece554_final_project/workout_classifier/workout_classifier.srcs/sources_1/bd/workout_classifier/ip/workout_classifier_rst_ps8_0_96M_0/workout_classifier_rst_ps8_0_96M_0.xci
# IP: The module: 'workout_classifier_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/ece554_final_project/workout_classifier/workout_classifier.gen/sources_1/bd/workout_classifier/ip/workout_classifier_rst_ps8_0_96M_0/workout_classifier_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'workout_classifier_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: z:/ece554_final_project/workout_classifier/workout_classifier.gen/sources_1/bd/workout_classifier/ip/workout_classifier_rst_ps8_0_96M_0/workout_classifier_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'workout_classifier_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: z:/ece554_final_project/workout_classifier/workout_classifier.srcs/sources_1/bd/workout_classifier/ip/workout_classifier_rst_ps8_0_96M_0/workout_classifier_rst_ps8_0_96M_0.xci
# IP: The module: 'workout_classifier_rst_ps8_0_96M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/ece554_final_project/workout_classifier/workout_classifier.gen/sources_1/bd/workout_classifier/ip/workout_classifier_rst_ps8_0_96M_0/workout_classifier_rst_ps8_0_96M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'workout_classifier_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: z:/ece554_final_project/workout_classifier/workout_classifier.gen/sources_1/bd/workout_classifier/ip/workout_classifier_rst_ps8_0_96M_0/workout_classifier_rst_ps8_0_96M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'workout_classifier_rst_ps8_0_96M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
