# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/workout_classifier/workout_classifier.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==workout_classifier || ORIG_REF_NAME==workout_classifier} -quiet] -quiet

# IP: bd/workout_classifier/ip/workout_classifier_zynq_ultra_ps_e_0_0/workout_classifier_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==workout_classifier_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==workout_classifier_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/workout_classifier/ip/workout_classifier_axi_smc_0/workout_classifier_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==workout_classifier_axi_smc_0 || ORIG_REF_NAME==workout_classifier_axi_smc_0} -quiet] -quiet

# IP: bd/workout_classifier/ip/workout_classifier_rst_ps8_0_96M_0/workout_classifier_rst_ps8_0_96M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==workout_classifier_rst_ps8_0_96M_0 || ORIG_REF_NAME==workout_classifier_rst_ps8_0_96M_0} -quiet] -quiet

# IP: bd/workout_classifier/ip/workout_classifier_mlp_controller_0_2/workout_classifier_mlp_controller_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==workout_classifier_mlp_controller_0_2 || ORIG_REF_NAME==workout_classifier_mlp_controller_0_2} -quiet] -quiet

# XDC: z:/ece554_final_project/workout_classifier/workout_classifier.gen/sources_1/bd/workout_classifier/workout_classifier_ooc.xdc
